language: scala
scala:
- 2.11.6
- 2.10.5
script: sbt clean coverage test coverageAggregate
jdk:
- oraclejdk8
notifications:
  email:
    recipients:
    - ivan@vonnagy.net
after_success: "sbt coveralls"